background="#272822"
text="#f8f8f2"
subtle="#808080"
warning-text="#f92672"
text-special-one="#ae81ff"
text-special-two="#a6e22e"
top-bar-background="#f92672"
top-bar-text="#f8f8f2"
status-bar-background="#f92672"
status-bar-text="#f8f8f2"
status-bar-view-background="#ae81ff"
status-bar-view-text="#f8f8f2"
command-text="#f8f8f2"
list-selected-background="#f92672"
list-selected-text="#f8f8f2"
list-selected-inactive-background="#ae81ff"
list-selected-inactive-text="#f8f8f2"
controls-text="#f8f8f2"
controls-highlight="#a6e22e"
autocomplete-background="#272822"
autocomplete-text="#f8f8f2"
autocomplete-selected-background="#ae81ff"
autocomplete-selected-text="#f8f8f2"
button-color-one="#f92672"
button-color-two="#272822"
timeline-name-background="#272822"
timeline-name-text="#808080"

