background="#2E3440"
text="#ECEFF4"
subtle="#4C566A"
warning-text="#BF616A"
text-special-one="#8FBCBB"
text-special-two="#81A1C1"
top-bar-background="#5E81AC"
top-bar-text="#ECEFF4"
status-bar-background="#5E81AC"
status-bar-text="#ECEFF4"
status-bar-view-background="#8FBCBB"
status-bar-view-text="#f8f8f2"
list-selected-background="#5E81AC"
list-selected-text="#ECEFF4"
